### ISSUE TITLE
Error: Eos is not a constructor > dapp-services-node

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-dapp-network#4]
```
$ zeus --version
1.8.556
```

Using the following `.env`

```
NODEOS_CHAINID
NODEOS_HOST
NODEOS_PORT
DSP_ACCOUNT
DSP_PRIVATE_KEY
```

```
$ node services/dapp-services-node/index.js 

/root/all-dapp-services/services/dapp-services-node/common.js:160
var eosPrivate = new Eos(eosconfig);
                 ^

TypeError: Eos is not a constructor
    at Object.<anonymous> (/root/all-dapp-services/services/dapp-services-node/common.js:73:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (/root/all-dapp-services/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/all-dapp-services/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/all-dapp-services/services/dapp-services-node/index.js:8:102)
```

**Comment by DenisCarriere** [comment]
Seems to be fixed by changing `new Eos` => `new Eos.JsonRpc`

https://github.com/liquidapps-io/zeus-dapp-network/blob/master/dapp-services/services/dapp-services-node/common.js#L66

**Comment by DenisCarriere** [comment]
Also missing `fetch` as param

```
const rpc = new JsonRpc('http://127.0.0.1:8888', { fetch });
```
